=== Tachyonite/PawnmorpherInsects/Schemas/MorphDef.xsd
<?xml version="1.0" encoding="Windows-1252" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="include/Enums.xsd" />
	<xs:include schemaLocation="include/CommonComplex.xsd" />
	<xs:element name="Defs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pawnmorph.MorphDef" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element name="defName" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="race" type="AnimalRace" minOccurs="0" maxOccurs="1" />
							<xs:element name="group" type="MorphGroups" minOccurs="0" maxOccurs="1" />
							<xs:element name="associatedAnimals" type="ListOfStrings" minOccurs="0" maxOccurs="1" />
							<xs:element name="categories" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="li" type="MorphCategory" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="raceSettings" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:all>
										<xs:element name="statModifiers" type="StatModifiersList" minOccurs="0" maxOccurs="1" />
										<xs:element name="thoughtSettings" type="HybridThoughtSettings" maxOccurs="1" minOccurs="0" />
										<xs:element name="graphicsSettings" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="skinColorOverride" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="skinColorOverrideSecond" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="femaleSkinColorOverride" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="femaleSkinColorOverrideSecond" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="hairColorOverride" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="hairColorOverrideSecond" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="femaleHairColorOverride" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="femaleHairColorOverrideSecond" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="customDrawSize" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="customHeadDrawSize" type="xs:string" minOccurs="0" maxOccurs="1" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="traitSettings" type="TraitSettings" minOccurs="0" maxOccurs="1" />
										<xs:element name="explicitHybridRace" type="xs:string" minOccurs="0" maxOccurs="1" />
										<xs:element name="transferHumanBodyAddons" type="xs:boolean" minOccurs="0" maxOccurs="1" />
										<xs:element name="requiredMutations" type="ListOfStrings" minOccurs="0" maxOccurs="1" />
									</xs:all>
								</xs:complexType>
							</xs:element>
							<xs:element name="transformSettings" type="TransformationSettings" minOccurs="0" maxOccurs="1" />
							<xs:element name="fullTransformation" type="xs:string" minOccurs="0" />
							<xs:element name="partialTransformation" type="xs:string" minOccurs="0"/>
							<xs:element name="addedAspects" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" type="AddedAspect" minOccurs="1" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="classification" type="AnimalClassification" minOccurs="0"/>
						</xs:all>
						<xs:attribute name="ParentName" type="xs:string" use="optional" />
						<xs:attribute name="Name" type="xs:string" use="optional" />
						<xs:attribute name="Abstract" type="xs:boolean" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="StatModifiersList">
		<xs:sequence>
			<xs:element name="li" type="StatModifier" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StatModifier">
		<xs:sequence>
			<xs:element name="stat" type="xs:string" />
			<xs:element name="value" type="xs:float" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HybridThoughtSettings">
		<xs:sequence>
			<xs:element name="replacerList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="original" type="xs:string" />
									<xs:element name="replacer" type="xs:string" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ateAnimalThought" minOccurs="0" maxOccurs="1" type="AteThought"></xs:element>
			<xs:element name="butcheredAnimalThought" type="ButcherThought" minOccurs="0" maxOccurs="1" />
			<xs:element name="suppressHumanlikeCannibalThoughts" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="canEatRaw" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="thoughtsBlackList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" type="xs:string" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ateThoughtsSpecifics" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" type="AteThought" minOccurs="1" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="butcherThoughtsSpecifics" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" maxOccurs="unbounded" type="ButcherThought" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AteThought">
		<xs:sequence>
			<xs:element name="thought" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="thoughtCannibal" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ingredientThought" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ingredientThoughtCannibal" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="raceList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" type="xs:string" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ButcherThought">
		<xs:sequence>
			<xs:element name="thought" type="xs:string" />
			<xs:element name="knowThought" type="xs:string" />
			<xs:element name="raceList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" type="xs:string" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TransformationSettings">
		<xs:sequence>
			<xs:element name="transformationTale" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="transformationMessageID" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="messageDef" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="transformationMemory" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="revertedMemory" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="revertedMemoryFurry" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="revertedMemoryBP" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TraitSettings">
		<xs:sequence>
			<xs:element name="forcedTraits" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="chance" type="xs:float" minOccurs="0" maxOccurs="1" />
									<xs:element name="commonalityMale" type="xs:float" minOccurs="0" maxOccurs="1" />
									<xs:element name="commonalityFemale" type="xs:float" minOccurs="0" maxOccurs="1" />
									<xs:element name="defName" type="xs:string" maxOccurs="1" minOccurs="1" />
									<xs:element name="degree" type="xs:int" maxOccurs="1" minOccurs="0" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AddedAspect">
		<xs:sequence>
			<xs:element name="def" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="keepOnReversion" type="xs:boolean" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Tachyonite/PawnmorpherInsects/Defs/Morphs/SpiderWeaver/SpiderWeaverMorph.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/MorphDef.xsd">
    <Pawnmorph.MorphDef ParentName="PMI_ProductionInsectBase">
        <defName>PMI_SpiderweaverMorph</defName>
        <race>VFEI_VatGrownSpiderweaver</race>
        <label>spiderweaver morph</label>
        <description>TODO</description>
        <fullTransformation>PMI_SpiderWeaverMorphTf</fullTransformation>
        <partialTransformation>PMI_SpiderWeaverMorphTfPartial</partialTransformation>
    </Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/PawnmorpherInsects/Defs/Morphs/RoyalMaggotMorph/RoyalMaggotMorph.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/MorphDef.xsd">
    <Pawnmorph.MorphDef ParentName="PMI_ProductionInsectBase">
        <defName>PMI_RoyalMaggotMorph</defName>
        <label>royal maggot morph</label>
        <description>TODO</description>
        <race>Megaspider</race>
        <fullTransformation>PMI_RoyalMaggotMorphTf</fullTransformation>
        <partialTransformation>PMI_RoyalMaggotMorphTfPartial</partialTransformation>
    </Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/PawnmorpherInsects/Defs/Morphs/MegaSpider/MSpiderMorph.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/MorphDef.xsd">
    <Pawnmorph.MorphDef ParentName="PMI_CombatInsectBase">
        <defName>PMI_MegaSpiderMorph</defName>
        <label>megaspider morph</label>
        <description>Megaspiders are feared across known space, and the humanoid morphs of them are no exception. Combining the ferocity in combat of the megaspider with the relative intellect of a human, these morphs are often very dangerous.</description>
        <race>Megaspider</race>
        <fullTransformation>PMI_MegaSpiderMorphTf</fullTransformation>
        <partialTransformation>PMI_MegaSpiderMorphTfPartial</partialTransformation>
    </Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/PawnmorpherInsects/1.3/Defs/Morphs/RoyalMaggotMorph/RoyalMaggot_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/MorphDef.xsd">
    <Pawnmorph.MorphDef ParentName="PMI_ProductionInsectBase">
        <defName>PMI_RoyalMaggotMorph</defName>
        <label>royal maggotmorph</label>
        <description>A foul odour and slimy trail follows these 'maggotmorphs' wherever they go. However, they do sometimes produce royal jelly, so some choose to keep them around for it.</description>
        <race>Megaspider</race>
        <fullTransformation>PMI_RoyalMaggotMorphTf</fullTransformation>
        <partialTransformation>PMI_RoyalMaggotMorphTfPartial</partialTransformation>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(154,125,94)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
    </Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/PawnmorpherInsects/1.3/Defs/Morphs/Invertebrates/Arachnid/Scorpion/GScorpion_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Tachyonite/Pawnmorpher/dev/Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="ArachnidMorph">
        <defName>PMI_GigaScorpionMorph</defName>
        <label>gigascorpion morph</label>
        <race>VFEI_VatGrownGigascorpion</race>
		<injectorDef>PMI_GScorpionInjector</injectorDef>
		<categories>
			<li>Combat</li>
		</categories>
        <fullTransformation>PMI_ScorpionMorphTf</fullTransformation>
        <partialTransformation>PMI_ScorpionMorphTfPartial</partialTransformation>
    </Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/PawnmorpherInsects/1.3/Defs/Morphs/Invertebrates/Insect/Gigawig/Gigawig_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Tachyonite/Pawnmorpher/dev/Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="InsectMorph">
        <defName>PMI_GigawigMorph</defName>
        <label>gigawigmorph</label>
        <description>Large and usually covered in thick plates of chitin, these  morphs are effective miners and prospectors.</description>
        <race>VFEI_VatGrownGigawig</race>
		<injectorDef>PMI_GigawigInjector</injectorDef>
		<categories>
			<li>PMI_Worker</li>
		</categories>
        <fullTransformation>PMI_GigawigMorphTf</fullTransformation>
        <partialTransformation>PMI_GigawigMorphTfPartial</partialTransformation>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(154,125,94)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
    </Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/PawnmorpherInsects/1.3/Defs/Morphs/Invertebrates/Arachnid/MegaSpider/MSpider_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Tachyonite/Pawnmorpher/dev/Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="ArachnidMorph">
        <defName>PMI_MegaSpiderMorph</defName>
        <label>megaspider morph</label>
        <description>Megaspiders are feared across known space, and the humanoid morphs of them are no exception. Combining the ferocity in combat of the megaspider with the relative intellect of a human, these morphs are often very dangerous.</description>
        <race>Megaspider</race>
		<injectorDef>PMI_MegaSpiderInjector</injectorDef>
		<categories>
			<li>Combat</li>
		</categories>
        <fullTransformation>PMI_MegaSpiderMorphTf</fullTransformation>
        <partialTransformation>PMI_MegaSpiderMorphTfPartial</partialTransformation>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(154,125,94)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
    </Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/PawnmorpherInsects/Defs/Morphs/Gigawig/GigawigMorph.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/MorphDef.xsd">
    <Pawnmorph.MorphDef ParentName="PMI_WorkerInsectBase">
        <defName>PMI_GigawigMorph</defName>
        <label>gigawigmorph</label>
        <description>Large and usually covered in thick plates of chitin, these  morphs are effective miners and prospectors.</description>
        <race>VFEI_VatGrownGigawig</race>
        <fullTransformation>PMI_GigawigMorphTf</fullTransformation>
        <partialTransformation>PMI_GigawigMorphTfPartial</partialTransformation>
    </Pawnmorph.MorphDef>
</Defs>
