=== Tachyonite/PawnmorpherInsects/Schemas/ThoughtDef.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="DefExtensions/FilterExtensions.xsd" />
	<xs:element name="Defs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ThoughtDef" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element name="defName" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="thoughtClass" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="workerClass" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="durationDays" type="xs:float" minOccurs="0" maxOccurs="1" />
							<xs:element name="morph" type="xs:string" maxOccurs="1" minOccurs="0" />
							<xs:element name="aspect" type="xs:string" maxOccurs="1" minOccurs="0" />
							<xs:element name="hediff" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="showBubble" type="xs:boolean" minOccurs="0"/>
							<xs:element name="icon" type="xs:string" minOccurs="0"/>
							<xs:element name="validWhileDespawned" type="xs:boolean" minOccurs="0"/>
							<xs:element name="requiredTraits" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="nullifyingTraits" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" minOccurs="1" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="stages" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" type="ThoughtStage" minOccurs="1" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="modExtensions" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" type="xs:anyType" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:all>
						<xs:attribute name="ParentName" type="AbstractThoughts" use="optional" />
						<xs:attribute name="Abstract" type="xs:boolean" use="optional" />
						<xs:attribute name="Name" type="xs:string" use="optional" />
						<xs:attribute name="Class" type="ThoughtDefClasses" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<xs:simpleType name="ThoughtDefClasses">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Pawnmorph.Thoughts.Def_MorphThought" />
			<xs:enumeration value="Pawnmorph.Thoughts.Def_AspectThought" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="AbstractThoughts">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OutlookMemoryBase" />
			<xs:enumeration value="GroupThoughtBase" />
			<xs:enumeration value="FH_NakedThought"/>
			<xs:enumeration value="FH_PersistentThought" />
			<xs:enumeration value="FH_NakedThougthNudist" />
			<xs:enumeration value="FH_MemoryBase"/>
			<xs:enumeration value="FH_FeralPillBase" />
			<xs:enumeration value="SapientAnimalBondedMasterBase" />
			<xs:enumeration value="SapientAnimalBondedNonMasterBase" />
			<xs:enumeration value="FormerHumanCannibalThoughtBase" />
			<xs:enumeration value="FormerHumanCannibalThoughtGoodBase" />
			<xs:enumeration value="AnimalisticPersistentThoughtBase" />
			<xs:enumeration value="DefaultReactionBase"/>
			<xs:enumeration value="SapientMemoryBase" />
			<xs:enumeration value="AnimalisticNakedThought" />
			<xs:enumeration value="AnimalisticNakedThougthNudist" />
			<xs:enumeration value="MergedPawnPersistentBase" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="ThoughtStage">
		<xs:all>
			<xs:element name="label" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="labelSocial" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="visible" type="xs:boolean" default="true" minOccurs="0" maxOccurs="1" />
			<xs:element name="baseMoodEffect" type="xs:float" minOccurs="0" maxOccurs="1" />
		</xs:all>
	</xs:complexType>
</xs:schema>

=== Tachyonite/PawnmorpherInsects/1.4/Defs/Morphs/Invertebrates/Invertebrates_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Tachyonite/Pawnmorpher/dev/Schemas/ThoughtDef.xsd">

	<ThoughtDef ParentName="OutlookMemoryBase">
		<defName>PMI_InvertebratesTransformationMemory</defName>
		<stages>
			<li>
				<label>morphed</label>
				<description>I'm... a bug? everything is so alien now.</description>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
			<li>
				<label>morphed</label>
				<description>Being a bug makes everything so new and exciting</description>
				<baseMoodEffect>+3</baseMoodEffect>
			</li>
			<li>
				<label>morphed</label>
				<description>This is even worse then I thought...I turned into a bug!</description>
				<baseMoodEffect>-5</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<defName>PMI_InvertebratesRevertedMemory</defName>
		<stages>
			<li>
				<label>reverted</label>
				<description>Back to normal!</description>
				<baseMoodEffect>3</baseMoodEffect>
			</li>
			<li>
				<label>reverted</label>
				<description>I was just getting used to it too.</description>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
			<li>
				<label>reverted</label>
				<description>Thank Randy, my bones are on the inside now, where they should be!</description>
				<baseMoodEffect>10</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>PMI_ChitainMemory</defName>
		<stages>
			<li>
				<label>Exoskeleton</label>
				<description>This is making it much harder to move</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Exoskeleton</label>
				<description>I feel like I'm wearing a coat of armor</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Exoskeleton</label>
				<description>this is so gross! and I can't feel anything anymore</description>
				<visible>true</visible>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>PMI_AntennaMemory</defName>
		<stages>
			<li>
				<label>Antenna</label>
				<description>These things keep getting in the way</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Antenna</label>
				<description>These are so cute, and I can feel the air move around me!</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Antenna</label>
				<description>I can't stand these things, everything sounds wrong now</description>
				<visible>true</visible>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>PMI_CompoundEyesMemory</defName>
		<stages>
			<li>
				<label>Compound Eyes</label>
				<description>Everything looks different and wrong</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Antenna</label>
				<description>Everything is so colorful</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Antenna</label>
				<description>I think I'm going to be sick</description>
				<visible>true</visible>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
		
</Defs>

=== Tachyonite/PawnmorpherInsects/1.4/Defs/Morphs/Invertebrates/Arachnid/Scorpion/GScorpion_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Tachyonite/Pawnmorpher/dev/Schemas/ThoughtDef.xsd">
	<ThoughtDef ParentName="OutlookMemoryBase">
        <durationDays>1</durationDays>
        <defName>PMI_ScorpionTailMemory</defName>
        <stages>
            <li>
                <label>Scorpion Tail</label>
                <description>This thing is so unwieldy</description>
                <visible>true</visible>
                <baseMoodEffect>-1</baseMoodEffect>
            </li>
            <li>
                <label>Scorpion Tail</label>
                <description>No one will mess with me now!</description>
                <visible>true</visible>
                <baseMoodEffect>2</baseMoodEffect>
            </li>
            <li>
                <label>Scorpion Tail</label>
                <description>It's so dangerous and hard to control. Get it off!</description>
                <visible>true</visible>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
</Defs>
